Completed react-events
kevin-l1/c0523-code-solutions pull request #78
Opened 2023-06-25 18:06 UTC by kevin-l1

![image](https://github.com/kevin-l1/c0523-code-solutions/assets/131307476/8564ce0f-58d1-4f88-9db0-3a4a6049c249)

2023-06-27 15:34 UTC, shawnkost requested changes
Couple tweaks here Kevin!

2023-06-27 15:34 UTC, shawnkost commented on react-events/my-app/src/App.js
> +          onCustomClick={() => handleCustomClick('Clicked red Good Morning')}
You shouldn't be passing a callback function. Inside your `handleCustomClick` function, that's where you should have the logic for `Clicked color`. We want to take advantage of the `text` & `color` props that get passed down, and not hard code them here. You should just be passing a reference to the function.

`onCustomClick={handleCustomClick}`

2023-06-27 15:34 UTC, shawnkost commented on react-events/my-app/src/CustomButton.js
> +    <button style={{background: color}} onClick={onCustomClick}>
This is where you'd do the callback function for the color

2023-06-28 19:09 UTC, TimelikeClosure approved these changes

2023-09-11 01:52 UTC, merged